trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

# Debug
- script: |
    echo "Root:"
    ls -la
    echo "Infra folder:"
    ls -la infra
  displayName: "Check files"

# Install Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# Init
- task: TerraformTask@5
  displayName: "Terraform Init"
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'infra'
    backendType: 'local'   # ✅ THIS LINE FIXES YOUR ERROR
- task: TerraformTask@5
  displayName: "Terraform Init"
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'infra'
    backendType: 'local'   # ✅ ADD THIS

# Plan ✅ FIXED
- task: TerraformTask@5
  displayName: "Terraform Plan"
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'infra'   # ✅ IMPORTANT
    environmentServiceNameAzureRM: 'terraform-secret'
    environmentAzureRmOverrideSubscriptionID: '6349a94a-bcc7-4da7-8f36-2f6bc3017bf7'

# Apply ✅ FIXED
- task: TerraformTask@5
  displayName: "Terraform Apply"
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'infra'   # ✅ IMPORTANT
    environmentServiceNameAzureRM: 'terraform-secret'
    environmentAzureRmOverrideSubscriptionID: '6349a94a-bcc7-4da7-8f36-2f6bc3017bf7'