trigger:
- main

variables:
- group: terraform-secrets

stages:

# ================= DEV =================
- stage: Dev
  displayName: Deploy Dev
  jobs:
  - template: templates/terraform-deploy.yml
    parameters:
      environment: dev

# ================= APPROVE UAT =================
- stage: ApproveUAT
  displayName: Approve UAT Deployment
  dependsOn: Dev
  condition: succeeded()
  jobs:
  - template: templates/manual-approval.yml
    parameters:
      instructions: Approve deployment to UAT

# ================= UAT =================
- stage: UAT
  displayName: Deploy UAT
  dependsOn: ApproveUAT
  condition: succeeded()
  jobs:
  - template: templates/terraform-deploy.yml
    parameters:
      environment: uat

# ================= APPROVE PROD =================
- stage: ApproveProd
  displayName: Approve Prod Deployment
  dependsOn: UAT
  condition: succeeded()
  jobs:
  - template: templates/manual-approval.yml
    parameters:
      instructions: Approve deployment to Production

# ================= PROD =================
- stage: Prod
  displayName: Deploy Prod
  dependsOn: ApproveProd
  condition: succeeded()
  jobs:
  - template: templates/terraform-deploy.yml
    parameters:
      environment: prod