trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: terraform-secrets

parameters:
- name: environment
  displayName: Select Environment
  type: string
  default: dev
  values:
    - dev
    - uat
    - prod

steps:

- checkout: self

- script: |
    echo "Root:"
    ls -la
    echo "Infra:"
    ls -la infra
  displayName: "Check Files"

# Install Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.6'

# Terraform Init
- task: TerraformTaskV4@4
  displayName: "Terraform Init"
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: 'infra'
    backendServiceArm: 'terraform-secret'
    backendAzureRmResourceGroupName: 'tf-backend-rg'
    backendAzureRmStorageAccountName: 'tfstate12345demomilan245'
    backendAzureRmContainerName: 'tfstate-${{ parameters.environment }}'
    backendAzureRmKey: '${{ parameters.environment }}.terraform.tfstate'

# Terraform Plan
- task: TerraformTaskV4@4
  displayName: "Terraform Plan"
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: 'infra'
    environmentServiceNameAzureRM: 'terraform-secret'
    commandOptions: >
      -var="environment=${{ parameters.environment }}"
      -var-file=${{ parameters.environment }}.tfvars
      -out=tfplan
  env:
    TF_VAR_vm_password: $(vm-password)

# Terraform Apply
- task: TerraformTaskV4@4
  displayName: "Terraform Apply"
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'infra'
    environmentServiceNameAzureRM: 'terraform-secret'
    commandOptions: 'tfplan'
  env:
    TF_VAR_vm_password: $(vm-password)