parameters:
- name: instructions
  type: string

jobs:
- job: Approval
  displayName: Manual Approval

  pool: server

  steps:
  - task: ManualValidation@0
    timeoutInMinutes: 1440
    inputs:
      notifyUsers: 'deepanshu.v7@gmail.com'
      instructions: ${{ parameters.instructions }}
      onTimeout: reject